/*
 * PaperDistill
 * Copyright (c) 2026 Petr Nazarov, Luxembourg Institute of Health (LIH)
 *
 * Released under the MIT License.
 * Developed with significant assistance from Anthropic Claude Code.
 * Responsibility for any bugs remains under active investigation.
 *
 * See LICENSE for details.
 */

import type { LLMInput, LLMOutput, LLMProvider } from "./base";

/**
 * Deterministic provider used to exercise the batch pipeline (prompt
 * building, atomic writes, run logging) without a real LLM backend.
 * Not exposed in the provider selector; used for internal testing only.
 */
export class MockProvider implements LLMProvider {
  async generateMarkdown(input: LLMInput): Promise<LLMOutput> {
    const text = [
      "# Mock Extraction",
      "",
      `- Model: ${input.model}`,
      `- Prompt length: ${input.userPrompt.length} characters`,
      "",
      "This Markdown was generated by the mock provider for pipeline testing.",
    ].join("\n");

    return { text };
  }
}
