import type { LLMInput, LLMOutput, LLMProvider } from "./base";

/**
 * Deterministic provider used to exercise the batch pipeline (prompt
 * building, atomic writes, run logging) without a real LLM backend.
 * Not exposed in the provider selector; used for internal testing only.
 */
export class MockProvider implements LLMProvider {
  async generateMarkdown(input: LLMInput): Promise<LLMOutput> {
    const text = [
      "# Mock Extraction",
      "",
      `- Model: ${input.model}`,
      `- Prompt length: ${input.userPrompt.length} characters`,
      "",
      "This Markdown was generated by the mock provider for pipeline testing.",
    ].join("\n");

    return { text };
  }
}
